// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MediawikiTranslator.Models.Data.MHRS;
//
//    var armorMsg = ArmorMsg.FromJson(jsonString);

namespace MediawikiTranslator.Models.Data.MHRS
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public partial class ArmorMsg
	{
		[JsonProperty("msgs", NullValueHandling = NullValueHandling.Ignore)]
		public Dictionary<string, ArmorMsgMsg> Msgs { get; set; }

		[JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
		public object[] Attributes { get; set; }

		[JsonProperty("name_to_uuid", NullValueHandling = NullValueHandling.Ignore)]
		public Dictionary<string, Guid> NameToUuid { get; set; }
	}

	public partial class ArmorMsgMsg
	{
		[JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
		public string Name { get; set; }

		[JsonProperty("hash", NullValueHandling = NullValueHandling.Ignore)]
		public long? Hash { get; set; }

		[JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
		public object[] Attributes { get; set; }

		[JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
		public Content Content { get; set; }
	}

	public partial class Content
	{
		[JsonProperty("Japanese", NullValueHandling = NullValueHandling.Ignore)]
		public string Japanese { get; set; }

		[JsonProperty("English", NullValueHandling = NullValueHandling.Ignore)]
		public string English { get; set; }

		[JsonProperty("French", NullValueHandling = NullValueHandling.Ignore)]
		public string French { get; set; }

		[JsonProperty("Italian", NullValueHandling = NullValueHandling.Ignore)]
		public string Italian { get; set; }

		[JsonProperty("German", NullValueHandling = NullValueHandling.Ignore)]
		public string German { get; set; }

		[JsonProperty("Spanish", NullValueHandling = NullValueHandling.Ignore)]
		public string Spanish { get; set; }

		[JsonProperty("Russian", NullValueHandling = NullValueHandling.Ignore)]
		public string Russian { get; set; }

		[JsonProperty("Polish", NullValueHandling = NullValueHandling.Ignore)]
		public string Polish { get; set; }

		[JsonProperty("Dutch", NullValueHandling = NullValueHandling.Ignore)]
		public string Dutch { get; set; }

		[JsonProperty("Portuguese", NullValueHandling = NullValueHandling.Ignore)]
		public string Portuguese { get; set; }

		[JsonProperty("PortugueseBr", NullValueHandling = NullValueHandling.Ignore)]
		public string PortugueseBr { get; set; }

		[JsonProperty("Korean", NullValueHandling = NullValueHandling.Ignore)]
		public string Korean { get; set; }

		[JsonProperty("TransitionalChinese", NullValueHandling = NullValueHandling.Ignore)]
		public string TransitionalChinese { get; set; }

		[JsonProperty("SimplelifiedChinese", NullValueHandling = NullValueHandling.Ignore)]
		public string SimplelifiedChinese { get; set; }

		[JsonProperty("Finnish", NullValueHandling = NullValueHandling.Ignore)]
		public string Finnish { get; set; }

		[JsonProperty("Swedish", NullValueHandling = NullValueHandling.Ignore)]
		public string Swedish { get; set; }

		[JsonProperty("Danish", NullValueHandling = NullValueHandling.Ignore)]
		public string Danish { get; set; }

		[JsonProperty("Norwegian", NullValueHandling = NullValueHandling.Ignore)]
		public string Norwegian { get; set; }

		[JsonProperty("Czech", NullValueHandling = NullValueHandling.Ignore)]
		public string Czech { get; set; }

		[JsonProperty("Hungarian", NullValueHandling = NullValueHandling.Ignore)]
		public string Hungarian { get; set; }

		[JsonProperty("Slovak", NullValueHandling = NullValueHandling.Ignore)]
		public string Slovak { get; set; }

		[JsonProperty("Arabic", NullValueHandling = NullValueHandling.Ignore)]
		public string Arabic { get; set; }

		[JsonProperty("Turkish", NullValueHandling = NullValueHandling.Ignore)]
		public string Turkish { get; set; }

		[JsonProperty("Bulgarian", NullValueHandling = NullValueHandling.Ignore)]
		public string Bulgarian { get; set; }

		[JsonProperty("Greek", NullValueHandling = NullValueHandling.Ignore)]
		public string Greek { get; set; }

		[JsonProperty("Romanian", NullValueHandling = NullValueHandling.Ignore)]
		public string Romanian { get; set; }

		[JsonProperty("Thai", NullValueHandling = NullValueHandling.Ignore)]
		public string Thai { get; set; }

		[JsonProperty("Ukrainian", NullValueHandling = NullValueHandling.Ignore)]
		public string Ukrainian { get; set; }

		[JsonProperty("Vietnamese", NullValueHandling = NullValueHandling.Ignore)]
		public string Vietnamese { get; set; }

		[JsonProperty("Indonesian", NullValueHandling = NullValueHandling.Ignore)]
		public string Indonesian { get; set; }

		[JsonProperty("Fiction", NullValueHandling = NullValueHandling.Ignore)]
		public string Fiction { get; set; }

		[JsonProperty("Hindi", NullValueHandling = NullValueHandling.Ignore)]
		public string Hindi { get; set; }

		[JsonProperty("LatinAmericanSpanish", NullValueHandling = NullValueHandling.Ignore)]
		public string LatinAmericanSpanish { get; set; }
	}

	public partial class ArmorMsg
	{
		public static ArmorMsg FromJson(string json) => JsonConvert.DeserializeObject<ArmorMsg>(json, MediawikiTranslator.Models.Data.MHRS.ArmorMsgConverter.Settings);
	}

	internal static class ArmorMsgConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
