// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class ChargeBlade
	{
		[JsonProperty("snow.equip.ChargeAxeBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipChargeAxeBaseUserData SnowEquipChargeAxeBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\chargeaxe\chargeaxebasedata.user.2.json")).SnowEquipChargeAxeBaseUserData.Param;
		}
	}

	public partial class SnowEquipChargeAxeBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public ChargeBladeParam[] Param { get; set; }
	}

	public partial class ChargeBladeParam : Weapon
	{
		[JsonProperty("_ChargeAxeBottleType", NullValueHandling = NullValueHandling.Ignore)]
		public string ChargeAxeBottleType { get; set; }
	}

	public partial class ChargeBlade
	{
		public static ChargeBlade FromJson(string json) => JsonConvert.DeserializeObject<ChargeBlade>(json, MediawikiTranslator.Models.Data.MHRS.ChargeBladeConverter.Settings);
	}

	internal static class ChargeBladeConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
