// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class Decorations
	{
		[JsonProperty("snow.data.DecorationsBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowDataDecorationsBaseUserData SnowDataDecorationsBaseUserData { get; set; }

		public static DecorationsParam[] GetDecorations()
		{
			SkillsParam[] allSkills = Skills.GetSkills();
			DecorationsParam[] src = FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\equip\decorations\decorationsbasedata.user.2.json")).SnowDataDecorationsBaseUserData.Param;
			List<DecorationsParam> ret = [];
			foreach (DecorationsParam deco in src)
			{
				string decoId = deco.Id!.Substring(deco.Id!.LastIndexOf('_') + 1);
				deco.Name = CommonMsgs.GetMsg($"Decorations_{decoId}_Name");
				if (string.IsNullOrEmpty(deco.Name) && Convert.ToInt32(decoId) < 999)
				{
					deco.Name = CommonMsgs.GetMsg($"Decorations_{decoId.Substring(1)}_Name");
				}
				deco.Explain = CommonMsgs.GetMsg($"Decorations_{decoId}_Explain");
				if (string.IsNullOrEmpty(deco.Explain) && Convert.ToInt32(decoId) < 999)
				{
					deco.Explain = CommonMsgs.GetMsg($"Decorations_{decoId.Substring(1)}_Explain").Replace("\r\n", " ");
				}
				deco.Skills = new SkillsParam[deco.SkillIdList.Length];
				int cntr = 0;
				foreach (string skillId in deco.SkillIdList)
				{
#nullable enable
					SkillsParam? match = allSkills.FirstOrDefault(x => x.Id! == skillId);
					if (match != null)
					{
						deco.Skills[cntr] = match;
					}
#nullable disable
					cntr++;
				}
				if (!deco.Name.Contains("<COLOR FF0000>#Rejected#</COLOR>"))
				{
					ret.Add(deco);
				}
			}
			return [..ret];
		}


		private static string GetDecoId(long id)
		{
			return new Dictionary<long, string>()
			{
				{ 1, "Decorations_000" },
				{ 2, "Decorations_001" },
				{ 3, "Decorations_002" },
				{ 4, "Decorations_003" },
				{ 5, "Decorations_004" },
				{ 6, "Decorations_005" },
				{ 7, "Decorations_006" },
				{ 8, "Decorations_007" },
				{ 9, "Decorations_008" },
				{ 10, "Decorations_009" },
				{ 11, "Decorations_010" },
				{ 12, "Decorations_011" },
				{ 13, "Decorations_012" },
				{ 14, "Decorations_013" },
				{ 15, "Decorations_014" },
				{ 16, "Decorations_015" },
				{ 17, "Decorations_016" },
				{ 18, "Decorations_017" },
				{ 19, "Decorations_018" },
				{ 20, "Decorations_019" },
				{ 21, "Decorations_020" },
				{ 22, "Decorations_021" },
				{ 23, "Decorations_022" },
				{ 24, "Decorations_023" },
				{ 25, "Decorations_024" },
				{ 26, "Decorations_025" },
				{ 27, "Decorations_026" },
				{ 28, "Decorations_027" },
				{ 29, "Decorations_028" },
				{ 30, "Decorations_029" },
				{ 31, "Decorations_030" },
				{ 32, "Decorations_031" },
				{ 33, "Decorations_032" },
				{ 34, "Decorations_033" },
				{ 35, "Decorations_034" },
				{ 36, "Decorations_035" },
				{ 37, "Decorations_036" },
				{ 38, "Decorations_037" },
				{ 39, "Decorations_038" },
				{ 40, "Decorations_039" },
				{ 41, "Decorations_040" },
				{ 42, "Decorations_041" },
				{ 43, "Decorations_042" },
				{ 44, "Decorations_043" },
				{ 45, "Decorations_044" },
				{ 46, "Decorations_045" },
				{ 47, "Decorations_046" },
				{ 48, "Decorations_047" },
				{ 49, "Decorations_048" },
				{ 50, "Decorations_049" },
				{ 51, "Decorations_050" },
				{ 52, "Decorations_051" },
				{ 53, "Decorations_052" },
				{ 54, "Decorations_053" },
				{ 55, "Decorations_054" },
				{ 56, "Decorations_055" },
				{ 57, "Decorations_056" },
				{ 58, "Decorations_057" },
				{ 59, "Decorations_058" },
				{ 60, "Decorations_059" },
				{ 61, "Decorations_060" },
				{ 62, "Decorations_061" },
				{ 63, "Decorations_062" },
				{ 64, "Decorations_063" },
				{ 65, "Decorations_064" },
				{ 66, "Decorations_065" },
				{ 67, "Decorations_066" },
				{ 68, "Decorations_067" },
				{ 69, "Decorations_068" },
				{ 70, "Decorations_069" },
				{ 71, "Decorations_070" },
				{ 72, "Decorations_071" },
				{ 73, "Decorations_072" },
				{ 74, "Decorations_073" },
				{ 75, "Decorations_074" },
				{ 76, "Decorations_075" },
				{ 77, "Decorations_076" },
				{ 78, "Decorations_077" },
				{ 79, "Decorations_078" },
				{ 80, "Decorations_079" },
				{ 81, "Decorations_080" },
				{ 82, "Decorations_081" },
				{ 83, "Decorations_082" },
				{ 84, "Decorations_083" },
				{ 85, "Decorations_084" },
				{ 86, "Decorations_085" },
				{ 87, "Decorations_086" },
				{ 88, "Decorations_087" },
				{ 89, "Decorations_088" },
				{ 90, "Decorations_089" },
				{ 91, "Decorations_090" },
				{ 92, "Decorations_091" },
				{ 93, "Decorations_092" },
				{ 94, "Decorations_093" },
				{ 95, "Decorations_094" },
				{ 96, "Decorations_095" },
				{ 97, "Decorations_096" },
				{ 98, "Decorations_097" },
				{ 99, "Decorations_098" },
				{ 100, "Decorations_099" },
				{ 101, "Decorations_100" },
				{ 102, "Decorations_101" },
				{ 103, "Decorations_102" },
				{ 104, "Decorations_103" },
				{ 105, "Decorations_104" },
				{ 106, "Decorations_105" },
				{ 107, "Decorations_106" },
				{ 108, "Decorations_107" },
				{ 109, "Decorations_0200" },
				{ 110, "Decorations_0201" },
				{ 111, "Decorations_0202" },
				{ 112, "Decorations_0203" },
				{ 113, "Decorations_0204" },
				{ 114, "Decorations_0205" },
				{ 115, "Decorations_0206" },
				{ 116, "Decorations_0207" },
				{ 117, "Decorations_0208" },
				{ 118, "Decorations_0209" },
				{ 119, "Decorations_0210" },
				{ 120, "Decorations_0211" },
				{ 121, "Decorations_0212" },
				{ 122, "Decorations_0213" },
				{ 123, "Decorations_0214" },
				{ 124, "Decorations_0215" },
				{ 125, "Decorations_0216" },
				{ 126, "Decorations_0217" },
				{ 127, "Decorations_0218" },
				{ 128, "Decorations_0219" },
				{ 129, "Decorations_0220" },
				{ 130, "Decorations_0221" },
				{ 131, "Decorations_0222" },
				{ 132, "Decorations_0223" },
				{ 133, "Decorations_0224" },
				{ 134, "Decorations_0225" },
				{ 135, "Decorations_0226" },
				{ 136, "Decorations_0227" },
				{ 137, "Decorations_0228" },
				{ 138, "Decorations_0229" },
				{ 139, "Decorations_0230" },
				{ 140, "Decorations_0231" },
				{ 141, "Decorations_0232" },
				{ 142, "Decorations_0233" },
				{ 143, "Decorations_0234" },
				{ 144, "Decorations_0235" },
				{ 145, "Decorations_0236" },
				{ 146, "Decorations_0237" },
				{ 147, "Decorations_0238" },
				{ 148, "Decorations_0239" },
				{ 149, "Decorations_0240" },
				{ 150, "Decorations_0241" },
				{ 151, "Decorations_0242" },
				{ 152, "Decorations_0243" },
				{ 153, "Decorations_0244" },
				{ 154, "Decorations_0245" },
				{ 155, "Decorations_0246" },
				{ 156, "Decorations_0247" },
				{ 157, "Decorations_0248" },
				{ 158, "Decorations_0249" },
				{ 159, "Decorations_0250" },
				{ 160, "Decorations_0251" },
				{ 161, "Decorations_0252" },
				{ 162, "Decorations_0253" },
				{ 163, "Decorations_0254" },
				{ 164, "Decorations_0255" },
				{ 165, "Decorations_0256" },
				{ 166, "Decorations_0257" },
				{ 167, "Decorations_0258" },
				{ 168, "Decorations_0259" },
				{ 169, "Decorations_0260" },
				{ 170, "Decorations_0261" },
				{ 171, "Decorations_0262" },
				{ 172, "Decorations_0263" },
				{ 173, "Decorations_0264" },
				{ 174, "Decorations_0265" },
				{ 175, "Decorations_0266" },
				{ 176, "Decorations_0267" },
				{ 177, "Decorations_0268" },
				{ 178, "Decorations_0269" },
				{ 179, "Decorations_0270" },
				{ 180, "Decorations_0271" },
				{ 181, "Decorations_0272" },
				{ 182, "Decorations_0273" },
				{ 183, "Decorations_0274" },
				{ 184, "Decorations_0275" },
				{ 185, "Decorations_0276" },
				{ 186, "Decorations_0277" },
				{ 187, "Decorations_0278" },
				{ 188, "Decorations_0279" },
				{ 189, "Decorations_0280" },
				{ 190, "Decorations_0281" },
				{ 191, "Decorations_0282" },
				{ 192, "Decorations_0283" },
				{ 193, "Decorations_0284" },
				{ 194, "Decorations_0285" },
				{ 195, "Decorations_0286" },
				{ 196, "Decorations_0287" },
				{ 197, "Decorations_0288" },
				{ 198, "Decorations_0289" },
				{ 199, "Decorations_0290" },
				{ 200, "Decorations_0291" },
				{ 201, "Decorations_0292" },
				{ 202, "Decorations_0293" },
				{ 203, "Decorations_0294" },
				{ 204, "Decorations_0295" },
				{ 205, "Decorations_0296" },
				{ 206, "Decorations_0297" },
				{ 207, "Decorations_0298" },
				{ 208, "Decorations_0299" },
				{ 209, "Decorations_0300" },
				{ 210, "Decorations_0301" },
				{ 211, "Decorations_0302" },
				{ 212, "Decorations_0303" },
				{ 213, "Decorations_0304" },
				{ 214, "Decorations_0305" },
				{ 215, "Decorations_0306" },
				{ 216, "Decorations_0307" },
				{ 217, "Decorations_0308" },
				{ 218, "Decorations_0309" },
				{ 219, "Decorations_0310" },
				{ 220, "Decorations_0311" },
				{ 221, "Decorations_0312" },
				{ 222, "Decorations_0313" },
				{ 223, "Decorations_0314" },
				{ 224, "Decorations_0315" },
				{ 225, "Decorations_0316" },
				{ 226, "Decorations_0317" },
				{ 227, "Decorations_0318" },
				{ 228, "Decorations_0319" },
				{ 229, "Decorations_0320" },
				{ 230, "Decorations_0321" },
				{ 231, "Decorations_0322" },
				{ 232, "Decorations_0323" },
				{ 233, "Decorations_0324" },
				{ 234, "Decorations_0325" },
				{ 235, "Decorations_0326" },
				{ 236, "Decorations_0327" },
				{ 237, "Decorations_0328" },
				{ 238, "Decorations_0329" },
				{ 239, "Decorations_0330" },
				{ 240, "Decorations_0331" },
				{ 241, "Decorations_0332" },
				{ 242, "Decorations_0333" },
				{ 243, "Decorations_0334" },
				{ 244, "Decorations_0335" },
				{ 245, "Decorations_0336" },
				{ 246, "Decorations_0337" },
				{ 247, "Decorations_0338" },
				{ 248, "Decorations_0339" },
				{ 249, "Decorations_0340" },
				{ 250, "Decorations_0341" },
				{ 251, "Decorations_0342" },
				{ 252, "Decorations_0343" },
				{ 253, "Decorations_0344" },
				{ 254, "Decorations_0345" },
				{ 255, "Decorations_0346" },
				{ 256, "Decorations_0347" },
				{ 257, "Decorations_0348" },
				{ 258, "Decorations_0349" },
				{ 259, "Decorations_0350" },
				{ 260, "Decorations_0351" },
				{ 261, "Decorations_0352" },
				{ 262, "Decorations_0353" },
				{ 263, "Decorations_0354" },
				{ 1048576, "HyakuryuDeco_None" },
				{ 1048577, "HyakuryuDeco_000" },
				{ 1048578, "HyakuryuDeco_001" },
				{ 1048579, "HyakuryuDeco_002" },
				{ 1048580, "HyakuryuDeco_003" },
				{ 1048581, "HyakuryuDeco_004" },
				{ 1048582, "HyakuryuDeco_005" },
				{ 1048583, "HyakuryuDeco_006" },
				{ 1048584, "HyakuryuDeco_007" },
				{ 1048585, "HyakuryuDeco_008" },
				{ 1048586, "HyakuryuDeco_009" },
				{ 1048587, "HyakuryuDeco_010" },
				{ 1048588, "HyakuryuDeco_011" },
				{ 1048589, "HyakuryuDeco_012" },
				{ 1048590, "HyakuryuDeco_013" },
				{ 1048591, "HyakuryuDeco_014" },
				{ 1048592, "HyakuryuDeco_015" },
				{ 1048593, "HyakuryuDeco_016" },
				{ 1048594, "HyakuryuDeco_017" },
				{ 1048595, "HyakuryuDeco_018" },
				{ 1048596, "HyakuryuDeco_019" },
				{ 1048597, "HyakuryuDeco_020" },
				{ 1048598, "HyakuryuDeco_021" },
				{ 1048599, "HyakuryuDeco_022" },
				{ 1048600, "HyakuryuDeco_023" },
				{ 1048601, "HyakuryuDeco_024" },
				{ 1048602, "HyakuryuDeco_025" },
				{ 1048603, "HyakuryuDeco_026" },
				{ 1048604, "HyakuryuDeco_027" },
				{ 1048605, "HyakuryuDeco_028" },
				{ 1048606, "HyakuryuDeco_029" },
				{ 1048607, "HyakuryuDeco_030" },
				{ 1048608, "HyakuryuDeco_031" },
				{ 1048609, "HyakuryuDeco_032" },
				{ 1048610, "HyakuryuDeco_033" },
				{ 1048611, "HyakuryuDeco_034" },
				{ 1048612, "HyakuryuDeco_035" },
				{ 1048613, "HyakuryuDeco_036" },
				{ 1048614, "HyakuryuDeco_037" },
				{ 1048615, "HyakuryuDeco_038" },
				{ 1048616, "HyakuryuDeco_039" },
				{ 1048617, "HyakuryuDeco_040" },
				{ 1048618, "HyakuryuDeco_041" },
				{ 1048619, "HyakuryuDeco_042" },
				{ 1048620, "HyakuryuDeco_043" },
				{ 1048621, "HyakuryuDeco_044" },
				{ 1048622, "HyakuryuDeco_045" },
				{ 1048623, "HyakuryuDeco_046" },
				{ 1048624, "HyakuryuDeco_047" },
				{ 1048625, "HyakuryuDeco_048" },
				{ 1048626, "HyakuryuDeco_049" },
				{ 1048627, "HyakuryuDeco_050" },
				{ 1048628, "HyakuryuDeco_051" },
				{ 1048629, "HyakuryuDeco_052" },
				{ 1048630, "HyakuryuDeco_053" },
				{ 1048631, "HyakuryuDeco_054" },
				{ 1048632, "HyakuryuDeco_055" },
				{ 1048633, "HyakuryuDeco_056" },
				{ 1048634, "HyakuryuDeco_057" },
				{ 1048635, "HyakuryuDeco_058" },
				{ 1048636, "HyakuryuDeco_059" },
				{ 1048637, "HyakuryuDeco_060" },
				{ 1048638, "HyakuryuDeco_061" },
				{ 1048639, "HyakuryuDeco_062" },
				{ 1048640, "HyakuryuDeco_063" },
				{ 1048641, "HyakuryuDeco_064" },
				{ 1048642, "HyakuryuDeco_065" },
				{ 1048643, "HyakuryuDeco_066" },
				{ 1048644, "HyakuryuDeco_067" },
				{ 1048645, "HyakuryuDeco_068" },
				{ 1048646, "HyakuryuDeco_069" },
				{ 1048647, "HyakuryuDeco_070" },
				{ 1048648, "HyakuryuDeco_071" },
				{ 1048649, "HyakuryuDeco_072" },
				{ 1048650, "HyakuryuDeco_073" },
				{ 1048651, "HyakuryuDeco_074" },
				{ 1048652, "HyakuryuDeco_075" },
				{ 1048653, "HyakuryuDeco_076" },
				{ 1048654, "HyakuryuDeco_077" },
				{ 1048655, "HyakuryuDeco_078" },
				{ 1048656, "HyakuryuDeco_079" },
				{ 1048657, "HyakuryuDeco_080" },
				{ 1048658, "HyakuryuDeco_081" },
				{ 1048659, "HyakuryuDeco_082" },
				{ 1048660, "HyakuryuDeco_083" },
				{ 1048661, "HyakuryuDeco_084" },
				{ 1048662, "HyakuryuDeco_085" },
				{ 1048663, "HyakuryuDeco_086" },
				{ 1048664, "HyakuryuDeco_087" },
				{ 1048665, "HyakuryuDeco_088" },
				{ 1048666, "HyakuryuDeco_089" },
				{ 1048667, "HyakuryuDeco_090" },
				{ 1048668, "HyakuryuDeco_091" },
				{ 1048669, "HyakuryuDeco_092" },
				{ 1048670, "HyakuryuDeco_093" },
				{ 1048671, "HyakuryuDeco_094" },
				{ 1048672, "HyakuryuDeco_095" },
				{ 1048673, "HyakuryuDeco_096" },
				{ 1048674, "HyakuryuDeco_097" },
				{ 1048675, "HyakuryuDeco_098" },
				{ 1048676, "HyakuryuDeco_099" },
				{ 1048677, "HyakuryuDeco_100" },
				{ 1048678, "HyakuryuDeco_101" },
				{ 1048679, "HyakuryuDeco_102" },
				{ 1048680, "HyakuryuDeco_103" },
				{ 1048681, "HyakuryuDeco_104" },
				{ 1048682, "HyakuryuDeco_105" },
				{ 1048683, "HyakuryuDeco_106" },
				{ 1048684, "HyakuryuDeco_107" },
				{ 1048685, "HyakuryuDeco_108" },
				{ 1048686, "HyakuryuDeco_109" },
				{ 1048687, "HyakuryuDeco_110" },
				{ 1048688, "HyakuryuDeco_111" },
				{ 1048689, "HyakuryuDeco_112" },
				{ 1048690, "HyakuryuDeco_113" },
				{ 1048691, "HyakuryuDeco_114" },
				{ 1048692, "HyakuryuDeco_115" },
				{ 1048693, "HyakuryuDeco_116" },
				{ 1048694, "HyakuryuDeco_117" },
				{ 1048695, "HyakuryuDeco_118" },
				{ 1048696, "HyakuryuDeco_119" },
				{ 1048697, "HyakuryuDeco_120" },
				{ 1048698, "HyakuryuDeco_121" },
				{ 1048699, "HyakuryuDeco_122" },
				{ 1048700, "HyakuryuDeco_123" },
				{ 1048701, "HyakuryuDeco_124" },
				{ 1048702, "HyakuryuDeco_125" },
				{ 1048703, "HyakuryuDeco_126" },
				{ 1048704, "HyakuryuDeco_127" },
			}[id];
		}
	}

	public partial class SnowDataDecorationsBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public DecorationsParam[] Param { get; set; }
	}

	public partial class DecorationsParam
	{
		[JsonProperty("_Id", NullValueHandling = NullValueHandling.Ignore)]
		public string Id { get; set; }

		[JsonProperty("_SortId", NullValueHandling = NullValueHandling.Ignore)]
		public long? SortId { get; set; }

		[JsonProperty("_Rare", NullValueHandling = NullValueHandling.Ignore)]
		public string Rare { get; set; }

		[JsonProperty("_IconColor", NullValueHandling = NullValueHandling.Ignore)]
		public string IconColor { get; set; }

		[JsonProperty("_BasePrice", NullValueHandling = NullValueHandling.Ignore)]
		public long? BasePrice { get; set; }

		[JsonProperty("_DecorationLv", NullValueHandling = NullValueHandling.Ignore)]
		public string DecorationLv { get; set; }

		[JsonProperty("_SkillIdList", NullValueHandling = NullValueHandling.Ignore)]
		public string[] SkillIdList { get; set; }

		[JsonProperty("_SkillLvList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] SkillLvList { get; set; }

		[JsonIgnore]
		public string Name { get; set; }

		[JsonIgnore]
		public string Explain { get; set; }

		[JsonIgnore]
		public SkillsParam[] Skills { get; set; }
	}

	public partial class Decorations
	{
		public static Decorations FromJson(string json) => JsonConvert.DeserializeObject<Decorations>(json, MediawikiTranslator.Models.Data.MHRS.DecorationsConverter.Settings);
	}

	internal static class DecorationsConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
