// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class DualBlades
	{
		[JsonProperty("snow.equip.DualBladesBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipDualBladesBaseUserData SnowEquipDualBladesBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\dualblades\dualbladesbasedata.user.2.json")).SnowEquipDualBladesBaseUserData.Param;
		}
	}

	public partial class SnowEquipDualBladesBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public DualBladesParam[] Param { get; set; }
	}

	public partial class DualBladesParam : Weapon
	{
		[JsonProperty("_SubElementType", NullValueHandling = NullValueHandling.Ignore)]
		public string SubElementType { get; set; }

		[JsonProperty("_SubElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? SubElementVal { get; set; }
	}

	public partial class DualBlades
	{
		public static DualBlades FromJson(string json) => JsonConvert.DeserializeObject<DualBlades>(json, MediawikiTranslator.Models.Data.MHRS.DualBladesConverter.Settings);
	}

	internal static class DualBladesConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
