// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class HeavyBowGun
	{
		[JsonProperty("snow.equip.HeavyBowgunBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipHeavyBowgunBaseUserData SnowEquipHeavyBowgunBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\heavybowgun\heavybowgunbasedata.user.2.json")).SnowEquipHeavyBowgunBaseUserData.Param;
		}
	}

	public partial class SnowEquipHeavyBowgunBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public HeavyBowGunParam[] Param { get; set; }
	}

	public partial class HeavyBowGunParam : Weapon
	{
		[JsonProperty("_Fluctuation", NullValueHandling = NullValueHandling.Ignore)]
		public string Fluctuation { get; set; }

		[JsonProperty("_Reload", NullValueHandling = NullValueHandling.Ignore)]
		public string Reload { get; set; }

		[JsonProperty("_Recoil", NullValueHandling = NullValueHandling.Ignore)]
		public string Recoil { get; set; }

		[JsonProperty("_KakusanType", NullValueHandling = NullValueHandling.Ignore)]
		public string KakusanType { get; set; }

		[JsonProperty("_BulletEquipFlagList", NullValueHandling = NullValueHandling.Ignore)]
		public bool[] BulletEquipFlagList { get; set; }

		[JsonProperty("_BulletNumList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] BulletNumList { get; set; }

		[JsonProperty("_BulletTypeList", NullValueHandling = NullValueHandling.Ignore)]
		public string[] BulletTypeList { get; set; }

		[JsonProperty("_HeavyBowgunUniqueBulletType", NullValueHandling = NullValueHandling.Ignore)]
		public string HeavyBowgunUniqueBulletType { get; set; }
	}

	public partial class HeavyBowGun
	{
		public static HeavyBowGun FromJson(string json) => JsonConvert.DeserializeObject<HeavyBowGun>(json, MediawikiTranslator.Models.Data.MHRS.HeavyBowGunConverter.Settings);
	}

	internal static class HeavyBowGunConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
