// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class InsectGlaive
	{
		[JsonProperty("snow.equip.InsectGlaiveBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipInsectBaseUserData SnowEquipInsectBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\insectglaive\insectglaivebasedata.user.2.json")).SnowEquipInsectBaseUserData.Param;
		}
	}

	public partial class SnowEquipInsectBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public InsectGlaiveParam[] Param { get; set; }
	}

	public partial class InsectGlaiveParam : Weapon
	{
		[JsonProperty("_InsectGlaiveInsectLv", NullValueHandling = NullValueHandling.Ignore)]
		public string InsectGlaiveInsectLv { get; set; }
	}

	public partial class InsectGlaive
	{
		public static InsectGlaive FromJson(string json) => JsonConvert.DeserializeObject<InsectGlaive>(json, MediawikiTranslator.Models.Data.MHRS.InsectGlaiveConverter.Settings);
	}

	internal static class InsectGlaiveConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
