// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class ItemsExplain
	{
		[JsonProperty("msgs", NullValueHandling = NullValueHandling.Ignore)]
		public Dictionary<string, ItemsExplainMsg> Msgs { get; set; }

		[JsonProperty("name_to_uuid", NullValueHandling = NullValueHandling.Ignore)]
		public Dictionary<string, Guid> NameToUuid { get; set; }
	}

	public partial class ItemsExplainMsg
	{
		[JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
		public string[] Content { get; set; }

		[JsonProperty("hash", NullValueHandling = NullValueHandling.Ignore)]
		public long? Hash { get; set; }

		[JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
		public string Name { get; set; }
	}

	public partial class ItemsExplain
	{
		public static ItemsExplain FromJson(string json) => JsonConvert.DeserializeObject<ItemsExplain>(json, MediawikiTranslator.Models.Data.MHRS.ItemsExplainConverter.Settings);
	}

	public static class ItemsExplainSerialize
	{
		public static string ToJson(this ItemsExplain self) => JsonConvert.SerializeObject(self, MediawikiTranslator.Models.Data.MHRS.ItemsExplainConverter.Settings);
	}

	internal static class ItemsExplainConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
