// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class LongSword
	{
		[JsonProperty("snow.equip.LongSwordBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipLongSwordBaseUserData SnowEquipLongSwordBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\longsword\longswordbasedata.user.2.json")).SnowEquipLongSwordBaseUserData.Param;
		}
	}

	public partial class SnowEquipLongSwordBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public LongSwordParam[] Param { get; set; }
	}

	public partial class LongSwordParam : Weapon
	{
	}

	public partial class LongSword
	{
		public static LongSword FromJson(string json) => JsonConvert.DeserializeObject<LongSword>(json, MediawikiTranslator.Models.Data.MHRS.LongSwordConverter.Settings);
	}

	internal static class LongSwordConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
