// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class RampageSkills
	{
		[JsonProperty("snow.data.PlHyakuryuSkillBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowDataPlHyakuryuSkillBaseUserData SnowDataPlHyakuryuSkillBaseUserData { get; set; }

		public static RampageSkillsParam[] GetRampageSkills()
		{
			RampageSkillsParam[] allSkills = FromJson(File.ReadAllText(@"")).SnowDataPlHyakuryuSkillBaseUserData.Param;
			foreach (RampageSkillsParam skill in allSkills)
			{
				string key = GetSkillId(skill.Id!.Value);
				skill.Name = CommonMsgs.GetMsg($"HyakuryuSkill_{key}_Name");
				skill.Explain = CommonMsgs.GetMsg($"HyakuryuSkill_{key}_Explain");
			}
			return allSkills;
		}

		private static string GetSkillId(long id)
		{
			return new Dictionary<long, string>()
			{
				{ 1, "000" },
				{ 2, "001" },
				{ 3, "002" },
				{ 4, "003" },
				{ 5, "004" },
				{ 6, "005" },
				{ 7, "006" },
				{ 8, "007" },
				{ 9, "008" },
				{ 10, "009" },
				{ 11, "010" },
				{ 12, "011" },
				{ 13, "012" },
				{ 14, "013" },
				{ 15, "014" },
				{ 16, "015" },
				{ 17, "016" },
				{ 18, "017" },
				{ 19, "018" },
				{ 20, "019" },
				{ 21, "020" },
				{ 22, "021" },
				{ 23, "022" },
				{ 24, "023" },
				{ 25, "024" },
				{ 26, "025" },
				{ 27, "026" },
				{ 28, "027" },
				{ 29, "028" },
				{ 30, "029" },
				{ 31, "030" },
				{ 32, "031" },
				{ 33, "032" },
				{ 34, "033" },
				{ 35, "034" },
				{ 36, "035" },
				{ 37, "036" },
				{ 38, "037" },
				{ 39, "038" },
				{ 40, "039" },
				{ 41, "040" },
				{ 42, "041" },
				{ 43, "042" },
				{ 44, "043" },
				{ 45, "044" },
				{ 46, "045" },
				{ 47, "046" },
				{ 48, "047" },
				{ 49, "048" },
				{ 50, "049" },
				{ 51, "050" },
				{ 52, "051" },
				{ 53, "052" },
				{ 54, "053" },
				{ 55, "054" },
				{ 56, "055" },
				{ 57, "056" },
				{ 58, "057" },
				{ 59, "058" },
				{ 60, "059" },
				{ 61, "060" },
				{ 62, "061" },
				{ 63, "062" },
				{ 64, "063" },
				{ 65, "064" },
				{ 66, "065" },
				{ 67, "066" },
				{ 68, "067" },
				{ 69, "068" },
				{ 70, "069" },
				{ 71, "070" },
				{ 72, "071" },
				{ 73, "072" },
				{ 74, "073" },
				{ 75, "074" },
				{ 76, "075" },
				{ 77, "076" },
				{ 78, "077" },
				{ 79, "078" },
				{ 80, "079" },
				{ 81, "080" },
				{ 82, "081" },
				{ 83, "082" },
				{ 84, "083" },
				{ 85, "084" },
				{ 86, "085" },
				{ 87, "086" },
				{ 88, "087" },
				{ 89, "088" },
				{ 90, "089" },
				{ 91, "090" },
				{ 92, "091" },
				{ 93, "092" },
				{ 94, "093" },
				{ 95, "094" },
				{ 96, "095" },
				{ 97, "096" },
				{ 98, "097" },
				{ 99, "098" },
				{ 100, "099" },
				{ 101, "100" },
				{ 102, "101" },
				{ 103, "102" },
				{ 104, "103" },
				{ 105, "104" },
				{ 106, "105" },
				{ 107, "106" },
				{ 108, "107" },
				{ 109, "108" },
				{ 110, "109" },
				{ 111, "110" },
				{ 112, "111" },
				{ 113, "112" },
				{ 114, "113" },
				{ 115, "114" },
				{ 116, "115" },
				{ 117, "116" },
				{ 118, "117" },
				{ 119, "118" },
				{ 120, "119" },
				{ 121, "120" },
				{ 122, "121" },
				{ 123, "122" },
				{ 124, "123" },
				{ 125, "124" },
				{ 126, "125" },
				{ 127, "126" },
				{ 128, "127" },
				{ 129, "128" },
				{ 130, "129" },
				{ 131, "130" },
				{ 132, "131" },
				{ 133, "132" },
				{ 134, "133" },
				{ 135, "134" },
				{ 136, "135" },
				{ 137, "136" },
				{ 138, "137" },
				{ 139, "138" },
				{ 140, "139" },
				{ 141, "140" },
				{ 142, "141" },
				{ 143, "142" },
				{ 144, "143" },
				{ 145, "144" },
				{ 146, "145" },
				{ 147, "146" },
				{ 148, "147" },
				{ 149, "148" },
				{ 150, "149" },
				{ 151, "150" },
				{ 152, "151" },
				{ 153, "152" },
				{ 154, "153" },
				{ 155, "154" },
				{ 156, "155" },
				{ 157, "156" },
				{ 158, "157" },
				{ 159, "158" },
				{ 160, "159" },
				{ 161, "160" },
				{ 162, "161" },
				{ 163, "162" },
				{ 164, "163" },
				{ 165, "164" },
				{ 166, "165" },
				{ 167, "166" },
				{ 168, "167" },
				{ 169, "168" },
				{ 170, "169" },
				{ 171, "170" },
				{ 172, "171" },
				{ 173, "172" },
				{ 174, "173" },
				{ 175, "174" },
				{ 176, "175" },
				{ 177, "176" },
				{ 178, "177" },
				{ 179, "178" },
				{ 180, "179" },
				{ 181, "180" },
				{ 182, "181" },
				{ 183, "182" },
				{ 184, "183" },
				{ 185, "184" },
				{ 186, "185" },
				{ 187, "186" },
				{ 188, "187" },
				{ 189, "188" },
				{ 190, "189" },
				{ 191, "190" },
				{ 192, "191" },
				{ 193, "192" },
				{ 194, "193" },
				{ 195, "194" },
				{ 196, "195" },
				{ 197, "196" },
				{ 198, "197" },
				{ 199, "198" },
				{ 200, "199" },
				{ 201, "200" },
				{ 202, "201" },
				{ 203, "202" },
				{ 204, "203" },
				{ 205, "204" },
				{ 206, "205" },
				{ 207, "206" },
				{ 208, "207" },
				{ 209, "208" },
				{ 210, "209" },
				{ 211, "210" },
				{ 212, "211" },
				{ 213, "212" },
				{ 214, "213" },
				{ 215, "214" },
				{ 216, "215" },
				{ 217, "216" },
				{ 218, "217" },
				{ 219, "218" },
				{ 220, "219" },
				{ 221, "220" },
				{ 222, "221" },
				{ 223, "222" },
				{ 224, "223" },
				{ 225, "224" },
				{ 226, "225" },
				{ 227, "226" },
				{ 228, "227" },
				{ 229, "228" },
				{ 230, "229" },
				{ 231, "230" },
				{ 232, "231" },
				{ 233, "232" },
				{ 234, "233" },
				{ 235, "234" },
				{ 236, "235" },
				{ 237, "236" },
				{ 238, "237" },
				{ 239, "238" },
				{ 240, "239" },
				{ 241, "240" },
				{ 242, "241" },
				{ 243, "242" },
				{ 244, "243" },
				{ 245, "244" },
				{ 246, "245" },
				{ 247, "246" },
				{ 248, "247" },
				{ 249, "248" },
				{ 250, "249" },
				{ 251, "250" },
				{ 252, "251" },
				{ 253, "252" },
				{ 254, "253" },
				{ 255, "254" },
				{ 256, "255" },
				{ 257, "256" },
				{ 258, "257" },
				{ 259, "258" },
				{ 260, "259" },
				{ 261, "260" },
				{ 262, "261" },
				{ 263, "262" },
				{ 264, "263" },
				{ 265, "264" },
				{ 266, "265" },
				{ 267, "266" },
				{ 268, "267" },
				{ 269, "268" },
				{ 270, "269" },
				{ 271, "270" },
				{ 272, "271" },
				{ 273, "272" },
				{ 274, "273" },
				{ 275, "274" },
				{ 276, "275" },
				{ 277, "276" },
				{ 278, "277" },
				{ 279, "278" },
				{ 280, "279" },
				{ 281, "280" },
				{ 282, "281" },
				{ 283, "282" },
				{ 284, "283" },
				{ 285, "284" },
				{ 286, "285" },
				{ 287, "286" },
				{ 288, "287" },
				{ 289, "288" },
				{ 290, "289" },
				{ 291, "290" },
				{ 292, "291" },
				{ 293, "292" },
				{ 294, "293" },
				{ 295, "294" },
				{ 296, "295" },
				{ 297, "296" },
				{ 298, "297" },
				{ 299, "298" },
				{ 300, "299" },
				{ 301, "300" },
				{ 302, "301" },
				{ 303, "302" },
				{ 304, "303" },
				{ 305, "304" },
				{ 306, "305" },
				{ 307, "306" },
				{ 308, "307" },
				{ 309, "308" },
				{ 310, "309" },
				{ 311, "310" },
				{ 312, "311" },
				{ 313, "312" },
				{ 314, "313" },
				{ 315, "314" },
				{ 316, "315" },
				{ 317, "316" },
				{ 318, "317" },
				{ 319, "318" },
				{ 320, "319" },
				{ 321, "320" },
				{ 322, "321" },
				{ 323, "322" },
				{ 324, "323" },
				{ 325, "324" },
				{ 326, "325" },
				{ 327, "326" },
				{ 328, "327" },
				{ 329, "328" },
				{ 330, "329" },
				{ 331, "330" },
				{ 332, "331" },
				{ 333, "332" },
				{ 334, "333" },
				{ 335, "334" },
				{ 336, "335" },
				{ 337, "336" },
				{ 338, "337" },
				{ 339, "338" },
				{ 340, "339" },
				{ 341, "340" },
				{ 342, "341" },
				{ 343, "342" },
				{ 344, "343" },
				{ 345, "344" },
				{ 346, "345" },
				{ 347, "346" },
				{ 348, "347" },
				{ 349, "348" },
				{ 350, "349" },
				{ 351, "350" },
				{ 352, "351" },
				{ 353, "352" },
				{ 354, "353" },
				{ 355, "354" },
				{ 356, "355" },
				{ 357, "356" },
				{ 358, "357" },
				{ 359, "358" },
				{ 360, "359" },
				{ 361, "360" },
				{ 362, "361" },
				{ 363, "362" },
				{ 364, "363" },
				{ 365, "364" },
				{ 366, "365" },
				{ 367, "366" },
				{ 368, "367" },
				{ 369, "368" },
				{ 370, "369" },
				{ 371, "370" },
				{ 372, "371" },
				{ 373, "372" },
				{ 374, "373" },
				{ 375, "374" },
				{ 376, "375" },
				{ 377, "376" },
				{ 378, "377" },
				{ 379, "378" },
				{ 380, "379" },
				{ 381, "380" },
				{ 382, "381" },
				{ 383, "382" },
				{ 384, "383" },
				{ 385, "384" },
				{ 386, "385" },
				{ 387, "386" },
				{ 388, "387" },
				{ 389, "388" },
				{ 390, "389" },
				{ 391, "390" },
				{ 392, "391" },
				{ 393, "392" },
				{ 394, "393" },
				{ 395, "394" },
				{ 396, "395" },
				{ 397, "396" },
				{ 398, "397" },
				{ 399, "398" },
				{ 400, "399" },
				{ 401, "400" },
				{ 402, "401" },
				{ 403, "402" },
				{ 404, "403" },
				{ 405, "404" },
				{ 406, "405" },
				{ 407, "406" },
				{ 408, "407" },
				{ 409, "408" },
				{ 410, "409" },
				{ 411, "410" },
				{ 412, "411" },
				{ 413, "412" },
				{ 414, "413" },
				{ 415, "414" },
				{ 416, "415" },
				{ 417, "416" },
				{ 418, "417" },
				{ 419, "418" },
				{ 420, "419" },
				{ 421, "420" },
				{ 422, "421" },
				{ 423, "422" },
				{ 424, "423" },
				{ 425, "424" },
				{ 426, "425" },
				{ 427, "426" },
				{ 428, "427" },
				{ 429, "428" },
				{ 430, "429" },
				{ 431, "430" },
				{ 432, "431" },
				{ 433, "432" },
				{ 434, "433" },
				{ 435, "434" },
				{ 436, "435" },
				{ 437, "436" },
				{ 438, "437" },
				{ 439, "438" },
				{ 440, "439" },
				{ 441, "440" },
				{ 442, "441" },
				{ 443, "442" },
				{ 444, "443" },
				{ 445, "444" },
				{ 446, "445" },
				{ 447, "446" },
				{ 448, "447" },
				{ 449, "448" },
				{ 450, "449" },
				{ 451, "450" },
				{ 452, "451" },
				{ 453, "452" },
				{ 454, "453" },
				{ 455, "454" },
				{ 456, "455" },
				{ 457, "456" },
				{ 458, "457" },
				{ 459, "458" },
				{ 460, "459" },
				{ 461, "460" },
				{ 462, "461" },
				{ 463, "462" },
				{ 464, "463" },
				{ 465, "464" },
				{ 466, "465" },
				{ 467, "466" },
				{ 468, "467" },
				{ 469, "468" },
				{ 470, "469" },
				{ 471, "470" },
				{ 472, "471" },
				{ 473, "472" },
				{ 474, "473" },
				{ 475, "474" },
				{ 476, "475" },
				{ 477, "476" },
				{ 478, "477" },
				{ 479, "478" },
				{ 480, "479" },
				{ 481, "480" },
				{ 482, "481" },
				{ 483, "482" },
				{ 484, "483" },
				{ 485, "484" },
				{ 486, "485" },
				{ 487, "486" },
				{ 488, "487" },
				{ 489, "488" },
				{ 490, "489" },
				{ 491, "490" },
				{ 492, "491" },
				{ 493, "492" },
				{ 494, "493" },
				{ 495, "494" },
				{ 496, "495" },
				{ 497, "496" },
				{ 498, "497" },
				{ 499, "498" },
				{ 500, "499" },
				{ 501, "500" },
				{ 502, "501" },
				{ 503, "502" },
				{ 504, "503" },
				{ 505, "504" },
				{ 506, "505" },
				{ 507, "506" },
				{ 508, "507" },
				{ 509, "508" },
				{ 510, "509" },
				{ 511, "510" },
				{ 512, "511" }
			}[id];
		}
	}

	public partial class SnowDataPlHyakuryuSkillBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public RampageSkillsParam[] Param { get; set; }
	}

	public partial class RampageSkillsParam
	{
		[JsonProperty("_Id", NullValueHandling = NullValueHandling.Ignore)]
		public long? Id { get; set; }

		[JsonProperty("_IconColor", NullValueHandling = NullValueHandling.Ignore)]
		public long? IconColor { get; set; }

		[JsonProperty("_ApplyRule", NullValueHandling = NullValueHandling.Ignore)]
		public long? ApplyRule { get; set; }

		[JsonProperty("_AddAtk", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddAtk { get; set; }

		[JsonProperty("_AddDefList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddDefList { get; set; }

		[JsonProperty("_AddCriticalRateList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddCriticalRateList { get; set; }

		[JsonProperty("_AddMainElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddMainElementVal { get; set; }

		[JsonProperty("_AddSubElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddSubElementVal { get; set; }

		[JsonProperty("_AddBottleElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddBottleElementVal { get; set; }

		[JsonProperty("_AddInsectLv", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddInsectLv { get; set; }

		[JsonProperty("_AddRecoil", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddRecoil { get; set; }

		[JsonProperty("_AddReload", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddReload { get; set; }

		[JsonProperty("_AddFluctuation", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddFluctuation { get; set; }

		[JsonProperty("_AddBulletTypeList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddBulletTypeList { get; set; }

		[JsonProperty("_AddLbBulletNumList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddLbBulletNumList { get; set; }

		[JsonProperty("_AddHbBulletNumList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddHbBulletNumList { get; set; }

		[JsonProperty("_AddRapidShotList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] AddRapidShotList { get; set; }

		[JsonProperty("_AddBuildUpBottleType", NullValueHandling = NullValueHandling.Ignore)]
		public long? AddBuildUpBottleType { get; set; }

		[JsonProperty("_OverwriteFlagList", NullValueHandling = NullValueHandling.Ignore)]
		public bool[] OverwriteFlagList { get; set; }

		[JsonProperty("_OverwriteMainElementType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteMainElementType { get; set; }

		[JsonProperty("_OverwriteMainElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteMainElementVal { get; set; }

		[JsonProperty("_OverwriteSubElementType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteSubElementType { get; set; }

		[JsonProperty("_OverwriteSubElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteSubElementVal { get; set; }

		[JsonProperty("_OverwriteSharpnessValList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] OverwriteSharpnessValList { get; set; }

		[JsonProperty("_OverwriteTakumiValList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] OverwriteTakumiValList { get; set; }

		[JsonProperty("_OverwriteGlFireType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteGlFireType { get; set; }

		[JsonProperty("_OverwriteGlFireLv", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteGlFireLv { get; set; }

		[JsonProperty("_OverwriteConcertIdList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] OverwriteConcertIdList { get; set; }

		[JsonProperty("_OverwriteCAxeBottleType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteCAxeBottleType { get; set; }

		[JsonProperty("_OverwriteSAxeBottleType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteSAxeBottleType { get; set; }

		[JsonProperty("_OverwriteInsectLv", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteInsectLv { get; set; }

		[JsonProperty("_OverwriteHbUniqueBullet", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteHbUniqueBullet { get; set; }

		[JsonProperty("_OverwriteChargeTypeList", NullValueHandling = NullValueHandling.Ignore)]
		public long[] OverwriteChargeTypeList { get; set; }

		[JsonProperty("_OverwriteChargeStartLv", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteChargeStartLv { get; set; }

		[JsonProperty("_OverwriteCurveType", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteCurveType { get; set; }

		[JsonProperty("_OverwriteBottleEquipFlag", NullValueHandling = NullValueHandling.Ignore)]
		public long? OverwriteBottleEquipFlag { get; set; }

		[JsonIgnore]
		public string Name { get; set; }

		[JsonIgnore]
		public string Explain { get; set; }
	}

	public partial class RampageSkills
	{
		public static RampageSkills FromJson(string json) => JsonConvert.DeserializeObject<RampageSkills>(json, MediawikiTranslator.Models.Data.MHRS.RampageSkillsConverter.Settings);
	}

	internal static class RampageSkillsConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
