// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{
	public partial class SwitchAxe
	{
		[JsonProperty("snow.equip.SlashAxeBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipSlashAxeBaseUserData SnowEquipSlashAxeBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\slashaxe\slashaxebasedata.user.2.json")).SnowEquipSlashAxeBaseUserData.Param;
		}
	}

	public partial class SnowEquipSlashAxeBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public SwitchAxeParam[] Param { get; set; }
	}

	public partial class SwitchAxeParam : Weapon
	{

		[JsonProperty("_SlashAxeBottleType", NullValueHandling = NullValueHandling.Ignore)]
		public string SlashAxeBottleType { get; set; }

		[JsonProperty("_SlashAxeBottleElementVal", NullValueHandling = NullValueHandling.Ignore)]
		public long? SlashAxeBottleElementVal { get; set; }
	}

	public partial class SwitchAxe
	{
		public static SwitchAxe FromJson(string json) => JsonConvert.DeserializeObject<SwitchAxe>(json, MediawikiTranslator.Models.Data.MHRS.SwitchAxeConverter.Settings);
	}

	internal static class SwitchAxeConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
