// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class SwordAndShield
	{
		[JsonProperty("snow.equip.ShortSwordBaseUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowEquipShortSwordBaseUserData SnowEquipShortSwordBaseUserData { get; set; }

		public static Weapon[] Fetch()
		{
			return FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\shortsword\shortswordbasedata.user.2.json")).SnowEquipShortSwordBaseUserData.Param;
		}
	}

	public partial class SnowEquipShortSwordBaseUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public SwordAndShieldParam[] Param { get; set; }
	}

	public partial class SwordAndShieldParam : Weapon
	{
	}

	public partial class SwordAndShield
	{
		public static SwordAndShield FromJson(string json) => JsonConvert.DeserializeObject<SwordAndShield>(json, MediawikiTranslator.Models.Data.MHRS.SwordAndShieldConverter.Settings);
	}

	internal static class SwordAndShieldConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
