// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHRS
{

	public partial class WeaponCraftingData
	{
		[JsonProperty("snow.data.WeaponProductUserData", NullValueHandling = NullValueHandling.Ignore)]
		public SnowDataWeaponProductUserData SnowDataWeaponProductUserData { get; set; }

		public static WeaponCraftingDataParam[] GetCraftingData()
		{
			Items[] allItems = Items.Fetch();
			WeaponCraftingDataParam[] allData = FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHRS\natives\stm\data\define\player\weapon\weaponcrafting.json")).SnowDataWeaponProductUserData.Param;
			foreach (WeaponCraftingDataParam data in allData)
			{
				data.Items = new Items[data.Item.Count(x => x != "I_Unclassified_None")];
				for (int i = 0; i < data.Items.Length; i++)
				{
					if (data.Item[i] != "I_Unclassified_None")
					{
						data.Items[i] = allItems.First(x => x.Id == data.Item[i]);
					}
				}
			}
			return allData;
		}
	}

	public partial class SnowDataWeaponProductUserData
	{
		[JsonProperty("_Param", NullValueHandling = NullValueHandling.Ignore)]
		public WeaponCraftingDataParam[] Param { get; set; }
	}

	public partial class WeaponCraftingDataParam
	{
		[JsonProperty("_Id", NullValueHandling = NullValueHandling.Ignore)]
		public string Id { get; set; }

		[JsonProperty("_ItemFlag", NullValueHandling = NullValueHandling.Ignore)]
		public string ItemFlag { get; set; }

		[JsonProperty("_EnemyFlag", NullValueHandling = NullValueHandling.Ignore)]
		public string EnemyFlag { get; set; }

		[JsonProperty("_ProgressFlag", NullValueHandling = NullValueHandling.Ignore)]
		public string ProgressFlag { get; set; }

		[JsonProperty("_Item", NullValueHandling = NullValueHandling.Ignore)]
		public string[] Item { get; set; }

		[JsonProperty("_ItemNum", NullValueHandling = NullValueHandling.Ignore)]
		public long[] ItemNum { get; set; }

		[JsonProperty("_MaterialCategory", NullValueHandling = NullValueHandling.Ignore)]
		public string MaterialCategory { get; set; }

		[JsonProperty("_MaterialCategoryNum", NullValueHandling = NullValueHandling.Ignore)]
		public long? MaterialCategoryNum { get; set; }

		[JsonProperty("_OutputItem", NullValueHandling = NullValueHandling.Ignore)]
		public string[] OutputItem { get; set; }

		[JsonProperty("_OutputItemNum", NullValueHandling = NullValueHandling.Ignore)]
		public long[] OutputItemNum { get; set; }

		[JsonIgnore]
		public MHRS.Items[] Items { get; set; }
	}

	public partial class WeaponCraftingData
	{
		public static WeaponCraftingData FromJson(string json) => JsonConvert.DeserializeObject<WeaponCraftingData>(json, MediawikiTranslator.Models.Data.MHRS.WeaponCraftingDataConverter.Settings);
	}

	internal static class WeaponCraftingDataConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
