// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MediawikiTranslator.Models.DamageTable.PartsData;
//
//    var partsData = PartsData.FromJson(jsonString);

namespace MediawikiTranslator.Models.DamageTable.PartsData
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public partial class PartsData
	{
		[JsonProperty("app.user_data.EnemyPartsTypeData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataEnemyPartsTypeData AppUserDataEnemyPartsTypeData { get; set; }
	}

	public partial class AppUserDataEnemyPartsTypeData
	{
		[JsonProperty("_Values", NullValueHandling = NullValueHandling.Ignore)]
		public Value[] Values { get; set; }
	}

	public partial class Value
	{
		[JsonProperty("app.user_data.EnemyPartsTypeData.cData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataEnemyPartsTypeDataCData AppUserDataEnemyPartsTypeDataCData { get; set; }
	}

	public partial class AppUserDataEnemyPartsTypeDataCData
	{
		[JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
		public long? Index { get; set; }

		[JsonProperty("_EmPartsType", NullValueHandling = NullValueHandling.Ignore)]
		public string EmPartsType { get; set; }

		[JsonProperty("_IconType", NullValueHandling = NullValueHandling.Ignore)]
		public string IconType { get; set; }

		[JsonProperty("_EmPartsName", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? EmPartsName { get; set; }

		[JsonProperty("_EmRottenPartsName", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? EmRottenPartsName { get; set; }

		[JsonProperty("_EmPartsExp", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? EmPartsExp { get; set; }
	}

	public partial class PartsData
	{
		public static PartsData[] FromJson(string json) => JsonConvert.DeserializeObject<PartsData[]>(json, MediawikiTranslator.Models.DamageTable.PartsData.Converter.Settings);
	}

	public static class Serialize
	{
		public static string ToJson(this PartsData[] self) => JsonConvert.SerializeObject(self, MediawikiTranslator.Models.DamageTable.PartsData.Converter.Settings);
	}

	internal static class Converter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
