//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediawikiTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediawikiTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Name&quot;:&quot;Potion&quot;,&quot;Description&quot;:&quot;Restores a small amount of health.&quot;,&quot;WikiIconColor&quot;:&quot;Green&quot;,&quot;WikiIconName&quot;:&quot;Medicine&quot;,&quot;_Id&quot;:68157446,&quot;_CariableFilter&quot;:1,&quot;_Type&quot;:0,&quot;_Rare&quot;:0,&quot;_PlMaxCount&quot;:10,&quot;_OtMaxCount&quot;:10,&quot;_SortId&quot;:100,&quot;_Supply&quot;:false,&quot;_CanPutInOtDogPouch&quot;:false,&quot;_ShowItemWindow&quot;:true,&quot;_ShowActionWindow&quot;:false,&quot;_Infinite&quot;:false,&quot;_Default&quot;:false,&quot;_IconCanEat&quot;:false,&quot;_IconItemRank&quot;:0,&quot;_EffectRare&quot;:false,&quot;_IconChara&quot;:5,&quot;_IconColor&quot;:8,&quot;_SeType&quot;:0,&quot;_SellPrice&quot;:8,&quot;_BuyPrice&quot;:66,&quot;_ItemActionType&quot;:11,&quot;_RankType&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mhrs_items {
            get {
                return ResourceManager.GetString("mhrs items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mhwi_items {
            get {
                object obj = ResourceManager.GetObject("mhwi_items", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;0984acc3-46af-4537-ac70-b7fdc9f24f74&quot;: {
        ///        &quot;content&quot;: [
        ///            &quot;\u30bb\u30fc\u30d6\u30c7\u30fc\u30bf\u304c\u3042\u308a\u307e\u305b\u3093\u3002\r\n\u65b0\u898f\u306b\u30bb\u30fc\u30d6\u30c7\u30fc\u30bf\u3092\u4f5c\u6210\u3057\u307e\u3059\u3002&quot;,
        ///            &quot;No save data exists.\r\nCreating a new save data file.&quot;,
        ///            &quot;Aucune donn\u00e9e de sauvegarde existante.\r\nCr\u00e9ation de nouvelles donn\u00e9es de sauvegarde.&quot;,
        ///            &quot;Non sono stati trovati dati di salvataggio.\r\nCr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mhwilds_combined_msgs {
            get {
                return ResourceManager.GetString("mhwilds_combined_msgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MHWilds_PartNames_json {
            get {
                object obj = ResourceManager.GetObject("MHWilds_PartNames.json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MHWilds_PartTypeData_json {
            get {
                object obj = ResourceManager.GetObject("MHWilds_PartTypeData.json", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
