// <auto-generated />
using MediawikiTranslator.Models.ArmorSets;
using MediawikiTranslator.Models.Data.MHWI;
using MediawikiTranslator.Models.Data.MHWilds;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.Globalization;
namespace MediawikiTranslator.Models.Data.MHWilds
{

	public partial class Armor
	{
		[JsonProperty("app.user_data.ArmorData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataArmorData AppUserDataArmorData { get; set; }

		public static Armor[] GetArmors()
		{
			JArray seriesMsgs = JsonConvert.DeserializeObject<JObject>(Utilities.ReadAllText(@"D:\MH_Data Repo\MH_Data\Parsed Files\MHWilds\dtlnor rips\MHWs-in-json-main\natives\STM\GameDesign\Text\Excel_Equip\ArmorSeries.msg.23.json")).Value<JArray>("entries");
			JArray armorMsgs = JsonConvert.DeserializeObject<JObject>(Utilities.ReadAllText(@"D:\MH_Data Repo\MH_Data\Parsed Files\MHWilds\dtlnor rips\MHWs-in-json-main\natives\STM\GameDesign\Text\Excel_Equip\Armor.msg.23.json")).Value<JArray>("entries");
			Armor[] src = FromJson(Utilities.ReadAllText(@"D:\MH_Data Repo\MH_Data\Parsed Files\MHWilds\dtlnor rips\MHWs-in-json-main\natives\STM\GameDesign\Common\Equip\ArmorData.user.3.json"));
			ArmorSeries srcSeries = ArmorSeries.FromJson(Utilities.ReadAllText(@"D:\MH_Data Repo\MH_Data\Parsed Files\MHWilds\dtlnor rips\MHWs-in-json-main\natives\STM\GameDesign\Common\Equip\ArmorSeriesData.user.3.json"))[0];
			foreach (AppUserDataArmorDataCData val in src[0].AppUserDataArmorData.Values.Select(x => x.AppUserDataArmorDataCData))
			{
				if (val.Series.AppArmorDefSeriesSerializable.Value != "[1]ID_000")
				{
					val.ArmorSeries = srcSeries.AppUserDataArmorSeriesData.Values.FirstOrDefault(x => !string.IsNullOrEmpty(val.Series.AppArmorDefSeriesSerializable.Value) && x.AppUserDataArmorSeriesDataCData.Series.AppArmorDefSeriesSerializable.Value == val.Series.AppArmorDefSeriesSerializable.Value).AppUserDataArmorSeriesDataCData;
				}
				if (val.ArmorSeries == null)
				{
					//"NONE" series
					val.ArmorSeries = srcSeries.AppUserDataArmorSeriesData.Values.First().AppUserDataArmorSeriesDataCData;
				}
				val.Name = armorMsgs.First(x => x.Value<string>("guid") == val.NameId!.ToString()).Value<JArray>("content")[1].ToString();
				val.Explain = armorMsgs.First(x => x.Value<string>("guid") == val.ExplainId!.ToString()).Value<JArray>("content")[1].ToString();
				val.ArmorSeries.Name = seriesMsgs.First(x => x.Value<string>("guid") == val.ArmorSeries.NameId!.ToString()).Value<JArray>("content")[1].ToString();
			}
			return src;
		}

		public static WebToolkitData[] GetWebToolkitData(int? rarityUnder = null)
		{
			Armor[] src = GetArmors();
			SkillsExtraInfo[] extraInfo = SkillsExtraInfo.FromJson(Utilities.ReadAllText(@"D:\MH_Data Repo\MH_Data\Parsed Files\MHWI\mhwi skills extra info.json"));
			List<WebToolkitData> ret = [];
			AppUserDataArmorDataCData[] srcFix = [..src.First().AppUserDataArmorData.Values.Select(x => x.AppUserDataArmorDataCData)];
			foreach (AppUserDataArmorDataCData srcArmor in srcFix.OrderBy(x => x.ArmorSeries.Name))
			{
				WebToolkitData toolkitArmor = new WebToolkitData()
				{
					MaleFrontImg = $"MHWilds-{srcArmor.ArmorSeries.Name.Replace("β", "Beta").Replace("α", "Alpha").Replace("γ", "Gamma")} Armor Male Render 001.webp",
					FemaleFrontImg = $"MHWilds-{srcArmor.ArmorSeries.Name.Replace("β", "Beta").Replace("α", "Alpha").Replace("γ", "Gamma")} Armor Female Render 001.webp",
					SetName = srcArmor.ArmorSeries.Name,
					Rarity = Convert.ToInt32(srcArmor.ArmorSeries.Rare.AppItemDefRareSerializable.Value.Substring(srcArmor.ArmorSeries.Rare.AppItemDefRareSerializable.Value.IndexOf("RARE") + 4))
				};
				toolkitArmor.Rank = toolkitArmor.Rarity < 6 ? "Low Rank" : "High Rank";
				if (rarityUnder == null || toolkitArmor.Rarity < rarityUnder)
				{
					if (ret.Any(x => x.SetName == toolkitArmor.SetName))
					{
						toolkitArmor = ret.First(x => x.SetName == toolkitArmor.SetName);
					}
					List<Piece> pieces = [];
					if (toolkitArmor.Pieces != null)
					{
						pieces = [.. toolkitArmor.Pieces];
					}
					Piece newPiece = new Piece()
					{
						Name = srcArmor.Name,
						Defense = srcArmor.Defense,
						IconType = TranslateArmorTypeToIcon(srcArmor.PartsType.AppArmorDefArmorPartsSerializable.Value),
						FemaleImage = "MHWilds-" + srcArmor.Name + " Female Render 001.webp",
						MaleImage = "MHWilds-" + srcArmor.Name + " Male Render 001.webp"
					};
					pieces.Add(newPiece);
					toolkitArmor.Pieces = [.. pieces];
					if (!ret.Any(x => x.SetName == toolkitArmor.SetName))
					{
						ret.Add(toolkitArmor);
					}
				}
			}
			return [.. ret];
		}

		private static string TranslateArmorTypeToIcon(string type)
		{
			return new Dictionary<string, string>()
			{
				{ "[0]HELM", "Helmet" },
				{ "[1]BODY", "Chestplate" },
				{ "[2]ARM", "Armguards" },
				{ "[3]WAIST", "Waist" },
				{ "[4]LEG", "Leggings" },
			}[type];
		}
	}

	public partial class AppUserDataArmorData
	{
		[JsonProperty("_Values", NullValueHandling = NullValueHandling.Ignore)]
		public Value[] Values { get; set; }
	}

	public partial class Value
	{
		[JsonProperty("app.user_data.ArmorData.cData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataArmorDataCData AppUserDataArmorDataCData { get; set; }
	}

	public partial class AppUserDataArmorDataCData
	{
		[JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
		public long? Index { get; set; }

		[JsonProperty("_DataValue", NullValueHandling = NullValueHandling.Ignore)]
		public long? DataValue { get; set; }

		[JsonProperty("_Series", NullValueHandling = NullValueHandling.Ignore)]
		public Series Series { get; set; }

		[JsonProperty("_PartsType", NullValueHandling = NullValueHandling.Ignore)]
		public PartsType PartsType { get; set; }

		[JsonProperty("_Name", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? NameId { get; set; }

		[JsonProperty("_Explain", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? ExplainId { get; set; }

		[JsonProperty("_Defense", NullValueHandling = NullValueHandling.Ignore)]
		public long? Defense { get; set; }

		[JsonProperty("_Resistance", NullValueHandling = NullValueHandling.Ignore)]
		public long[] Resistance { get; set; }

		[JsonProperty("_SlotLevel", NullValueHandling = NullValueHandling.Ignore)]
		public SlotLevel[] SlotLevel { get; set; }

		[JsonProperty("_Skill", NullValueHandling = NullValueHandling.Ignore)]
		public Skill[] Skill { get; set; }

		[JsonProperty("_SkillLevel", NullValueHandling = NullValueHandling.Ignore)]
		public long[] SkillLevel { get; set; }

		[JsonIgnore]
		public string Name { get; set; }
		[JsonIgnore]
		public string Explain { get; set; }

		[JsonIgnore]
		public AppUserDataArmorSeriesDataCData ArmorSeries { get; set; }
	}

	public partial class PartsType
	{
		[JsonProperty("app.ArmorDef.ARMOR_PARTS_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public SeriesAppSerializable AppArmorDefArmorPartsSerializable { get; set; }
	}

	public partial class SeriesAppSerializable
	{
		[JsonProperty("_Value", NullValueHandling = NullValueHandling.Ignore)]
		public string Value { get; set; }
	}

	public partial class Series
	{
		[JsonProperty("app.ArmorDef.SERIES_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public SeriesAppSerializable AppArmorDefSeriesSerializable { get; set; }
	}

	public partial class Skill
	{
		[JsonProperty("app.HunterDef.Skill_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public SeriesAppSerializable AppHunterDefSkillSerializable { get; set; }
	}

	public partial class SlotLevel
	{
		[JsonProperty("app.EquipDef.SlotLevel_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public SeriesAppSerializable AppEquipDefSlotLevelSerializable { get; set; }
	}

	public partial class Armor
	{
		public static Armor[] FromJson(string json) => JsonConvert.DeserializeObject<Armor[]>(json, MediawikiTranslator.Models.Data.MHWilds.ArmorConverter.Settings);
	}

	public static class Serialize
	{
		public static string ToJson(this Armor[] self) => JsonConvert.SerializeObject(self, MediawikiTranslator.Models.Data.MHWilds.ArmorConverter.Settings);
	}

	internal static class ArmorConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}