// <auto-generated />
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace MediawikiTranslator.Models.Data.MHWilds
{

	public partial class ArmorSeries
	{
		[JsonProperty("app.user_data.ArmorSeriesData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataArmorSeriesData AppUserDataArmorSeriesData { get; set; }
	}

	public partial class AppUserDataArmorSeriesData
	{
		[JsonProperty("_Values", NullValueHandling = NullValueHandling.Ignore)]
		public Value[] Values { get; set; }
	}

	public partial class Value
	{
		[JsonProperty("app.user_data.ArmorSeriesData.cData", NullValueHandling = NullValueHandling.Ignore)]
		public AppUserDataArmorSeriesDataCData AppUserDataArmorSeriesDataCData { get; set; }
	}

	public partial class AppUserDataArmorSeriesDataCData
	{
		[JsonProperty("_Index", NullValueHandling = NullValueHandling.Ignore)]
		public long? Index { get; set; }

		[JsonProperty("_Series", NullValueHandling = NullValueHandling.Ignore)]
		public Series_Series Series { get; set; }

		[JsonProperty("_Name", NullValueHandling = NullValueHandling.Ignore)]
		public Guid? NameId { get; set; }

		[JsonProperty("_ModelVariety", NullValueHandling = NullValueHandling.Ignore)]
		public ModelVariety ModelVariety { get; set; }

		[JsonProperty("_ModId", NullValueHandling = NullValueHandling.Ignore)]
		public long? ModId { get; set; }

		[JsonProperty("_ModSubMaleId", NullValueHandling = NullValueHandling.Ignore)]
		public long? ModSubMaleId { get; set; }

		[JsonProperty("_ModSubFemaleId", NullValueHandling = NullValueHandling.Ignore)]
		public long? ModSubFemaleId { get; set; }

		[JsonProperty("_SortId", NullValueHandling = NullValueHandling.Ignore)]
		public long? SortId { get; set; }

		[JsonProperty("_Rare", NullValueHandling = NullValueHandling.Ignore)]
		public Rare Rare { get; set; }

		[JsonProperty("_Price", NullValueHandling = NullValueHandling.Ignore)]
		public long? Price { get; set; }

		[JsonProperty("_Color", NullValueHandling = NullValueHandling.Ignore)]
		public Color Color { get; set; }
		[JsonIgnore]
		public string Name { get; set; }
	}

	public partial class Color
	{
		[JsonProperty("app.ArmorDef.ARMOR_COLOR_TYPE_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public AppSerializable AppArmorDefArmorColorTypeSerializable { get; set; }
	}

	public partial class AppSerializable
	{
		[JsonProperty("_Value", NullValueHandling = NullValueHandling.Ignore)]
		public string Value { get; set; }
	}

	public partial class ModelVariety
	{
		[JsonProperty("app.ArmorDef.MODEL_VARIETY_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public AppSerializable AppArmorDefModelVarietySerializable { get; set; }
	}

	public partial class Rare
	{
		[JsonProperty("app.ItemDef.RARE_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public AppSerializable AppItemDefRareSerializable { get; set; }
	}

	public partial class Series_Series
	{
		[JsonProperty("app.ArmorDef.SERIES_Serializable", NullValueHandling = NullValueHandling.Ignore)]
		public AppSerializable AppArmorDefSeriesSerializable { get; set; }
	}

	public partial class ArmorSeries
	{
		public static ArmorSeries[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorSeries[]>(json, MediawikiTranslator.Models.Data.MHWilds.SeriesConverter.Settings);
	}

	internal static class SeriesConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
    }
}
