// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MediawikiTranslator.Models.Data.MHWI;
//
//    var armorCraftingData = ArmorCraftingData.FromJson(jsonString);

namespace MediawikiTranslator.Models.Data.MHWI
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using MediawikiTranslator.Models.ArmorSets;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public partial class ArmorCraftingData
	{
		[JsonProperty("Index", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Index { get; set; }

		[JsonProperty("EquipmentCategory", NullValueHandling = NullValueHandling.Ignore)]
		public string EquipmentCategory { get; set; }

		[JsonProperty("EquipmentIndex", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? EquipmentIndex { get; set; }

		[JsonProperty("EquipmentName", NullValueHandling = NullValueHandling.Ignore)]
		public string EquipmentName { get; set; }

		[JsonProperty("ItemToUnlockId", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? ItemToUnlockId { get; set; }

		[JsonProperty("ItemToUnlockName", NullValueHandling = NullValueHandling.Ignore)]
		public string ItemToUnlockName { get; set; }

		[JsonProperty("MonsterToUnlock", NullValueHandling = NullValueHandling.Ignore)]
		public string MonsterToUnlock { get; set; }

		[JsonProperty("StoryUnlock", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? StoryUnlock { get; set; }

		[JsonProperty("Unk1", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Unk1 { get; set; }

		[JsonProperty("ItemRank", NullValueHandling = NullValueHandling.Ignore)]
		public string ItemRank { get; set; }

		[JsonProperty("Mat1Id", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat1Id { get; set; }

		[JsonProperty("Mat1Name", NullValueHandling = NullValueHandling.Ignore)]
		public string Mat1Name { get; set; }

		[JsonProperty("Mat1Count", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat1Count { get; set; }

		[JsonProperty("Mat2Id", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat2Id { get; set; }

		[JsonProperty("Mat2Name", NullValueHandling = NullValueHandling.Ignore)]
		public string Mat2Name { get; set; }

		[JsonProperty("Mat2Count", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat2Count { get; set; }

		[JsonProperty("Mat3Id", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat3Id { get; set; }

		[JsonProperty("Mat3Name", NullValueHandling = NullValueHandling.Ignore)]
		public string Mat3Name { get; set; }

		[JsonProperty("Mat3Count", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat3Count { get; set; }

		[JsonProperty("Mat4Id", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat4Id { get; set; }

		[JsonProperty("Mat4Name", NullValueHandling = NullValueHandling.Ignore)]
		public string Mat4Name { get; set; }

		[JsonProperty("Mat4Count", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Mat4Count { get; set; }

		[JsonProperty("Unk2", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Unk2 { get; set; }

		[JsonProperty("Unk3", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Unk3 { get; set; }

		[JsonProperty("Unk4", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Unk4 { get; set; }

		[JsonProperty("Unk5", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? Unk5 { get; set; }

		[JsonIgnore]
		public Items Mat1 { get; set; }

		[JsonIgnore]
		public Items Mat2 { get; set; }

		[JsonIgnore]
		public Items Mat3 { get; set; }

		[JsonIgnore]
		public Items Mat4 { get; set; }

		public static ArmorCraftingData[] GetArmorCraftingData()
		{
			Items[] items = MHWI.Items.Fetch();
			ArmorCraftingData[] ret = FromJson(File.ReadAllText(@"D:\MH_Data Repo\MH_Data\Raw Data\MHWI\chunk\common\equip\armorcrafting.json"));
			foreach (ArmorCraftingData data in ret)
			{
				if (data.Mat1Id!.Value > 0)
				{
					data.Mat1 = items.First(x => x.Id!.Value == data.Mat1Id!.Value);
				}
				if (data.Mat2Id!.Value > 0)
				{
					data.Mat2 = items.First(x => x.Id!.Value == data.Mat2Id!.Value);
				}
				if (data.Mat3Id!.Value > 0)
				{
					data.Mat3 = items.First(x => x.Id!.Value == data.Mat3Id!.Value);
				}
				if (data.Mat4Id!.Value > 0)
				{
					data.Mat4 = items.First(x => x.Id!.Value == data.Mat4Id!.Value);
				}
			}
			return ret;
		}
	}

	public partial class ArmorCraftingData
	{
		public static ArmorCraftingData[] FromJson(string json) => JsonConvert.DeserializeObject<ArmorCraftingData[]>(json, MediawikiTranslator.Models.Data.MHWI.ArmorCraftingDataConverter.Settings);
	}

	internal static class ArmorCraftingDataConverter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}

	internal class ParseStringConverter : JsonConverter
	{
		public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

		public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
		{
			if (reader.TokenType == JsonToken.Null) return null;
			var value = serializer.Deserialize<string>(reader);
			long l;
			if (Int64.TryParse(value, out l))
			{
				return l;
			}
			throw new Exception("Cannot unmarshal type long");
		}

		public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
		{
			if (untypedValue == null)
			{
				serializer.Serialize(writer, null);
				return;
			}
			var value = (long)untypedValue;
			serializer.Serialize(writer, value.ToString());
			return;
		}

		public static readonly ParseStringConverter Singleton = new ParseStringConverter();
	}
}
