// <auto-generated />
namespace MediawikiTranslator.Models.Data.MHWI
{
	using DocumentFormat.OpenXml.ExtendedProperties;
	using MediawikiTranslator.Generators;
	using MediawikiTranslator.Models.Data.MHRS;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;
	using Newtonsoft.Json.Linq;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Diagnostics;
	using System.Globalization;

	public partial class Wrapper
	{
		[JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
		public ItemsDatum[] Data { get; set; }

		public static Models.Data.MHWI.ItemCrafting[] itemCrafting { get; set; } = Models.Data.MHWI.ItemCrafting.Fetch();
		public static Armor[] allArmor { get; set; } = Armor.GetArmors();
		public static WeaponCraftingData[] weaponCraft { get; set; } = WeaponCraftingData.GetCraftingData();
		public static WeaponForgingData[] weaponForge { get; set; } = WeaponForgingData.GetForgingData();
		public static GunnerData[] mhwiGuns { get; set; } = GunnerData.GetGunnerData();
		public static BlademasterData[] mhwiBlades { get; set; } = BlademasterData.GetBlademasterData();

		private static IEnumerable<string> Flat(JToken token)
		{
			switch (token.Type)
			{
				// nested value types
				case JTokenType.Object:
				case JTokenType.Array:
				case JTokenType.Property:
					foreach (var item in token.Children().Select(Flat).SelectMany(x => x))
						yield return item;
					break;
				default: // primitive values: int, string, float
					yield return token.ToString();
					break;
			}
		}
	}

	public partial class ItemsDatum
	{
		[JsonProperty("list", NullValueHandling = NullValueHandling.Ignore)]
		public Items[] List { get; set; }

		[JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
		public string Type { get; set; }

		[JsonProperty("GridName", NullValueHandling = NullValueHandling.Ignore)]
		public string GridName { get; set; }

		[JsonProperty("IsHidden", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsHidden { get; set; }

		[JsonProperty("IsAddingAllowed", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsAddingAllowed { get; set; }
	}

	public partial class Items
	{
		[JsonProperty("Magic_1", NullValueHandling = NullValueHandling.Ignore)]
		public long? Magic1 { get; set; }

		[JsonProperty("Magic_2", NullValueHandling = NullValueHandling.Ignore)]
		public long? Magic2 { get; set; }

		[JsonProperty("Entry_Count", NullValueHandling = NullValueHandling.Ignore)]
		public long? EntryCount { get; set; }

		[JsonProperty("Index", NullValueHandling = NullValueHandling.Ignore)]
		public long? Index { get; set; }

		[JsonProperty("UniqueId", NullValueHandling = NullValueHandling.Ignore)]
		[JsonConverter(typeof(ParseStringConverter))]
		public long? UniqueId { get; set; }

		[JsonProperty("ChangedItems", NullValueHandling = NullValueHandling.Ignore)]
		public object[] ChangedItems { get; set; }

		[JsonProperty("Id", NullValueHandling = NullValueHandling.Ignore)]
		public long? Id { get; set; }

		[JsonProperty("Sub_Type", NullValueHandling = NullValueHandling.Ignore)]
		public long? SubType { get; set; }

		[JsonProperty("Type", NullValueHandling = NullValueHandling.Ignore)]
		public long? Type { get; set; }

		[JsonProperty("Rarity", NullValueHandling = NullValueHandling.Ignore)]
		public long? Rarity { get; set; }

		[JsonProperty("Carry_Limit", NullValueHandling = NullValueHandling.Ignore)]
		public long? CarryLimit { get; set; }

		[JsonProperty("Carry_Limit_Non_IB_", NullValueHandling = NullValueHandling.Ignore)]
		public long? CarryLimitNonIb { get; set; }

		[JsonProperty("Sort_Order", NullValueHandling = NullValueHandling.Ignore)]
		public long? SortOrder { get; set; }

		[JsonProperty("Icon_Id", NullValueHandling = NullValueHandling.Ignore)]
		public long? IconId { get; set; }

		[JsonProperty("Icon_Color_Id", NullValueHandling = NullValueHandling.Ignore)]
		public long? IconColorId { get; set; }

		[JsonProperty("Is_Huge_Carryable", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsHugeCarryable { get; set; }

		[JsonProperty("Sell_Price", NullValueHandling = NullValueHandling.Ignore)]
		public long? SellPrice { get; set; }

		[JsonProperty("Buy_Price", NullValueHandling = NullValueHandling.Ignore)]
		public long? BuyPrice { get; set; }

		[JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
		public string Name { get; set; }

		[JsonProperty("Description", NullValueHandling = NullValueHandling.Ignore)]
		public string Description { get; set; }

		[JsonProperty("Flags", NullValueHandling = NullValueHandling.Ignore)]
		public long? Flags { get; set; }

		[JsonProperty("Has_Infinity_Symbol", NullValueHandling = NullValueHandling.Ignore)]
		public bool? HasInfinitySymbol { get; set; }

		[JsonProperty("Is_Supply_Item", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsSupplyItem { get; set; }

		[JsonProperty("Unknown", NullValueHandling = NullValueHandling.Ignore)]
		public bool? Unknown { get; set; }

		[JsonProperty("Is_Consumable", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsConsumable { get; set; }

		[JsonProperty("Is_Fey_or_Streamstone", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsFeyOrStreamstone { get; set; }

		[JsonProperty("Is_Infinite_Use", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsInfiniteUse { get; set; }

		[JsonProperty("Has_Star", NullValueHandling = NullValueHandling.Ignore)]
		public bool? HasStar { get; set; }

		[JsonProperty("Has_New_Palico_Gadget_Symbol", NullValueHandling = NullValueHandling.Ignore)]
		public bool? HasNewPalicoGadgetSymbol { get; set; }

		[JsonProperty("Is_Level_1", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsLevel1 { get; set; }

		[JsonProperty("Is_Level_2", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsLevel2 { get; set; }

		[JsonProperty("Is_Level_3", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsLevel3 { get; set; }

		[JsonProperty("Is_Shiny", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsShiny { get; set; }

		[JsonProperty("Is_Huge_Carriable", NullValueHandling = NullValueHandling.Ignore)]
		public bool? IsHugeCarriable { get; set; }

		[JsonProperty("Not_Storable_as_an_Item", NullValueHandling = NullValueHandling.Ignore)]
		public bool? NotStorableAsAnItem { get; set; }
		[NotMapped]
		public string Category
		{
			get
			{
				switch (Type)
				{
					case 0:
						string[] equipment = ["Capture Net", "Fishing Rod", "BBQ Spit", "Ghillie Mantle", "Temporal Mantle", "Health Booster", "Rocksteady Mantle", "Challenger Mantle", "Vitality Mantle", "Fireproof Mantle", "Waterproof Mantle", "Iceproof Mantle", "Thunderproof Mantle", "Dragonproof Mantle", "Cleanser Booster", "Glider Mantle", "Evasion Mantle", "Impact Mantle", "Apothecary Mantle", "Immunity Mantle", "Affinity Booster", "Bandit Mantle", "Vigorwasp Delivery", "Vigorwasp Station", "Flashfly Cage", "Thunderbug Cage", "Shieldspire Taunt", "Shieldspire Bash", "Coral Cheerhorn", "Coral Cheerbongo", "Plunderblade", "Palarang", "Meowlotov Assault", "Rath-of-Meow", "Igni Sign", "Hunter Runestone", "Assassin's Hood", "Surveyor Set", "Raider Ride", "Vigorwasp Revival", "Boombug Cage", "Shieldspire Stooge", "Coral Sonicgong", "Mount & Plunder", "Meowcano", "Tailraider Signal", "Bugtrappers: Fried Dragonfly", "Protectors: Dried Goldenfish", "Troupers: Horned Urchin", "Plunderers: Steamed Cricket", "Grimalkyne: Pot-au-magma", "Boaboa: Boaboa Bread", "Special Scope", "Snowball", "Snowman", "Green Herb", "Red Herb", "Mixed Herb (G+R)"];
						return equipment.Contains(Name) ? "Equipment" : "Consumables";
					case 1:
						return "Materials";
					case 2:
						return "Account Items";
					case 3:
						return "Ammo & Coatings";
					case 4:
						return "Jewels";
					case 5:
						return "Room Furnishings";
					default:
						return "???";
				}
			}
		}

		[NotMapped]
		public string WikiIconName
		{
			get
			{
				return new Dictionary<long, string>()
				{
					{ 0, "Pouch" },
					{ 1, "Mushroom" },
					{ 2, "Egg" },
					{ 3, "Webbing" },
					{ 4, "Herb" },
					{ 5, "Medicine" },
					{ 6, "Whetstone" },
					{ 7, "Meat" },
					{ 8, "Dung" },
					{ 9, "Ball" },
					{ 10, "Bomb" },
					{ 11, "Box" },
					{ 12, "Trap" },
					{ 13, "Sac" },
					{ 14, "Barrel" },
					{ 16, "Husk" },
					{ 17, "Ammo" },
					{ 18, "Bottle" },
					{ 19, "Coating" },
					{ 20, "Spiderweb" },
					{ 21, "Seed" },
					{ 22, "Ore" },
					{ 23, "Bug" },
					{ 24, "Smoke Bomb" },
					{ 25, "Coin" },
					{ 26, "Ticket" },
					{ 29, "Bait" },
					{ 30, "Boomerang" },
					{ 32, "Binoculars" },
					{ 33, "Knife" },
					{ 34, "Spit" },
					{ 36, "Book" },
					{ 37, "Charm" },
					{ 38, "Armor Sphere" },
					{ 39, "Decoration" },
					{ 41, "Monster Part" },
					{ 42, "Bone" },
					{ 43, "Scale" },
					{ 44, "Hide" },
					{ 45, "Claw" },
					{ 46, "Shell" },
					{ 47, "Pallium" },
					{ 50, "Meal Ticket" },
					{ 52, "Tail" },
					{ 58, "Question Mark" },
					{ 59, "Wing" },
					{ 60, "Head" },
					{ 61, "Plate" },
					{ 62, "Pill" },
					{ 64, "Capture Net" },
					{ 65, "Streamstone" },
					{ 66, "Decoration Level 1" },
					{ 67, "Decoration Level 2" },
					{ 68, "Decoration Level 3" },
					{ 70, "Rustshard" },
					{ 71, "Camera" },
					{ 72, "Decoration Level 4" },
					{ 76, "Dracolite" },
					{ 77, "Pod" },
					{ 78, "Ballista Ammo" },
					{ 79, "Cannon Ammo" },
					{ 81, "Igni Sign" },
					{ 82, "Hunter Runestone" },
					{ 83, "Furniture Room" },
					{ 84, "Furniture Curtain" },
					{ 85, "Furniture Sofa" },
					{ 86, "Furniture Bed" },
					{ 87, "Furniture Table" },
					{ 88, "Furniture Chair" },
					{ 89, "Furniture Plant" },
					{ 90, "Furniture Decor" },
					{ 91, "Furniture Light" },
					{ 92, "Endemic Life Mammal" },
					{ 93, "Endemic Life Bird" },
					{ 94, "Endemic Life Bug" },
					{ 95, "Endemic Life Fish" },
					{ 99, "Furniture Painting" },
					{ 100, "Furniture Meal" },
					{ 101, "Raider Ride" },
					{ 102, "Tailrider Signal" },
					{ 109, "Palico Tools" },
					{ 110, "NOT AVAILABLE" },
					{ 112, "Mantle" },
					{ 118, "Furniture Wall" },
					{ 119, "Pendant" },
					{ 120, "Weapon Base" },
					{ 159, "Furniture Music Player" },
					{ 255, "NOT AVAILABLE" }
				}[IconId.Value];
			}
		}

		[NotMapped]
		public string WikiIconColor
		{
			get
			{
				return GetColor(IconColorId.Value);
			}
		}

		private List<Generators.ItemCrafting> FetchCombinations(Items[] src)
		{
			List<Generators.ItemCrafting> ret = [];
			foreach (Models.Data.MHWI.ItemCrafting combination in Wrapper.itemCrafting.Where(x => x.ResultId == Id))
			{
				Models.Data.MHWI.Items matA = src.First(x => x.Id == combination.Mat1Id);
#pragma warning disable CS8669 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.
				Models.Data.MHWI.Items? matB = null;
#pragma warning restore CS8669 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.
				if (combination.Mat2Id != null && combination.Mat2Id > 0)
				{
					matB = src.First(x => x.Id == combination.Mat2Id);
				}
				ret.Add(new Generators.ItemCrafting()
				{
					MaterialA = matA.Name,
					MaterialB = matB?.Name ?? "",
					Number = (int)combination.Qty,
					Result = Name
				});
			}
			return ret;
		}

		private List<Generators.ItemEquipment> FetchEquipment()
		{
			List<Generators.ItemEquipment> res = [];
			foreach (BlademasterData obj in Wrapper.mhwiBlades)
			{
#nullable enable
				WeaponCraftingData? thisCraft = Wrapper.weaponCraft.FirstOrDefault(x => x.EquipmentId!.Value == obj.Index!.Value && x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
				if (obj.TreePosition > 0 && thisCraft != null && thisCraft.Mat1Id > 0)
				{
					WeaponCraftingData? parentCraft = Wrapper.weaponCraft.FirstOrDefault(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && (x.ChildIndex1!.Value == thisCraft.Index!.Value || x.ChildIndex2!.Value == thisCraft.Index!.Value || x.ChildIndex3!.Value == thisCraft.Index!.Value || x.ChildIndex4!.Value == thisCraft.Index!.Value));
					BlademasterData? parent = Wrapper.mhwiBlades.FirstOrDefault(x => parentCraft != null && x.WeaponType == obj.WeaponType && x.Name == parentCraft.EquipmentName);
					if (parent == null || parentCraft == null)
					{
						WeaponForgingData forge = Wrapper.weaponForge.First(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
						parent = Wrapper.mhwiBlades.FirstOrDefault(x => x.WeaponType == obj.WeaponType && x.Name == forge.EquipmentName);
					}
					if (Utilities.DoesMatchItem(parent, thisCraft, this))
					{
						res.Add(new ItemEquipment()
						{
							EquipmentName = parent!.Name,
							EquipmentType = "Weapon"
						});
					}
				}
#nullable disable
				if (Wrapper.weaponForge.Any(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_")))
				{
					WeaponForgingData forge = Wrapper.weaponForge.First(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
					if (Utilities.DoesForgeMatchItem(obj, forge, this))
					{
						res.Add(new ItemEquipment()
						{
							EquipmentName = obj!.Name,
							EquipmentType = "Weapon"
						});
					}
				}
				if (thisCraft != null)
				{
					if (thisCraft.ChildIndex1 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex1!.Value);
						BlademasterData child = Wrapper.mhwiBlades.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex2 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex2!.Value);
						BlademasterData child = Wrapper.mhwiBlades.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex3 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex3!.Value);
						BlademasterData child = Wrapper.mhwiBlades.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex4 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex4!.Value);
						BlademasterData child = Wrapper.mhwiBlades.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
				}
			}

			foreach (GunnerData obj in Wrapper.mhwiGuns)
			{
#nullable enable
				WeaponCraftingData? thisCraft = Wrapper.weaponCraft.FirstOrDefault(x => x.EquipmentId!.Value == obj.Index!.Value && x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
				if (obj.TreePosition > 0 && thisCraft != null && thisCraft.Mat1Id > 0)
				{
					WeaponCraftingData? parentCraft = Wrapper.weaponCraft.FirstOrDefault(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && (x.ChildIndex1!.Value == thisCraft.Index!.Value || x.ChildIndex2!.Value == thisCraft.Index!.Value || x.ChildIndex3!.Value == thisCraft.Index!.Value || x.ChildIndex4!.Value == thisCraft.Index!.Value));
					GunnerData? parent = Wrapper.mhwiGuns.FirstOrDefault(x => parentCraft != null && x.WeaponType == obj.WeaponType && x.Name == parentCraft.EquipmentName);
					if (parent == null || parentCraft == null)
					{
						WeaponForgingData forge = Wrapper.weaponForge.First(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
						parent = Wrapper.mhwiGuns.FirstOrDefault(x => x.WeaponType == obj.WeaponType && x.Name == forge.EquipmentName);
					}
					if (Utilities.DoesMatchItem(parent, thisCraft, this))
					{
						res.Add(new ItemEquipment()
						{
							EquipmentName = parent!.Name,
							EquipmentType = "Weapon"
						});
					}
				}
#nullable disable
				if (Wrapper.weaponForge.Any(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_")))
				{
					WeaponForgingData forge = Wrapper.weaponForge.First(x => x.EquipmentIndex!.Value == obj.Index!.Value && x.EquipmentType == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_"));
					if (Utilities.DoesForgeMatchItem(obj, forge, this))
					{
						res.Add(new ItemEquipment()
						{
							EquipmentName = obj!.Name,
							EquipmentType = "Weapon"
						});
					}
				}
				if (thisCraft != null)
				{
					if (thisCraft.ChildIndex1 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex1!.Value);
						GunnerData child = Wrapper.mhwiGuns.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex2 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex2!.Value);
						GunnerData child = Wrapper.mhwiGuns.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex3 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex3!.Value);
						GunnerData child = Wrapper.mhwiGuns.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
					if (thisCraft.ChildIndex4 > 0)
					{
						WeaponCraftingData childCraft = Wrapper.weaponCraft.First(x => x.EquipmentCategory == obj.WeaponType.Replace("Great Sword", "Greatsword").Replace("Long Sword", "Longsword").Replace(" ", "_") && x.Index!.Value == thisCraft.ChildIndex4!.Value);
						GunnerData child = Wrapper.mhwiGuns.First(x => x.WeaponType == obj.WeaponType && x.Index!.Value == childCraft.EquipmentId!.Value);
						if (Utilities.DoesMatchItem(child, childCraft, this))
						{
							res.Add(new ItemEquipment()
							{
								EquipmentName = child!.Name,
								EquipmentType = "Weapon"
							});
						}
					}
				}
			}
			res.AddRange(Wrapper.allArmor.Where(x => x.CraftingData != null && new long?[] { x.CraftingData.Mat1Id, x.CraftingData.Mat2Id, x.CraftingData.Mat3Id, x.CraftingData.Mat4Id }.Any(y => y != null && y.HasValue && y.Value == Id))
				.Select(x => new ItemEquipment()
				{
					EquipmentName = x.Name,
					EquipmentType = "Armor"
				}));
			return [.. res];
		}

		private List<Generators.ItemSource> FetchSources()
		{
			return [];
		}

		public static Generators.Items[] FetchParsed()
		{
			int order = 0;
			Items[] src = Fetch();
			return [..src.Select(item => new Generators.Items()
			{
				BuyPrice = (int)item.BuyPrice,
				CarryLimit = (int)item.CarryLimit,
				Category = item.Category,
				Combinations = item.FetchCombinations(src),
				Description = item.Description.Replace("<STYL MOJI_YELLOW_DEFAULT>", "<span style=\"color: #b29400;\">").Replace("</STYL>", "</span>"),
				Equipment = item.FetchEquipment(),
				InternalID = item.Id.Value.ToString(),
				InternalOrder = order++,
				JPName = Utilities.GetMHWIItemJPNName(item.Name),
				Name = item.Name,
				Rarity = (int)item.Rarity,
				SellPrice = (int)item.SellPrice,
				Sources = item.FetchSources(),
				WikiIconColor = item.WikiIconColor,
				WikiIconName = item.WikiIconName
			})];
		}

		public static string GetColor(long colorId)
		{
			return new Dictionary<long, string>()
				{
					{ 0, "White" },
					{ 1, "Red" },
					{ 2, "Green" },
					{ 3, "Blue" },
					{ 4, "Yellow" },
					{ 5, "Purple" },
					{ 6, "Light Blue" },
					{ 7, "Orange" },
					{ 8, "Pink" },
					{ 9, "Lemon" },
					{ 10, "Gray" },
					{ 11, "Brown" },
					{ 12, "Emerald" },
					{ 13, "Moss" },
					{ 14, "Rose" },
					{ 15, "Violet" },
					{ 16, "Dark Purple" },
					{ 17, "NOT AVAILABLE" },
					{ 18, "NOT AVAILABLE" },
					{ 19, "Purple" },
					{ 20, "NOT AVAILABLE" },
					{ 21, "NOT AVAILABLE" },
					{ 22, "NOT AVAILABLE" },
					{ 23, "NOT AVAILABLE" },
					{ 24, "Tan" },
					{ 25, "Vermilion" },
					{ 26, "Light Green" },
					{ 255, "NOT AVAILABLE" }
				}[colorId];
		}
	}

	public partial class Items
	{
		public static Items[] FromJson(string json) => JsonConvert.DeserializeObject<Wrapper>(json, MediawikiTranslator.Models.Data.MHWI.Converter.Settings).Data[1].List;
		public static Items[] Fetch() => FromJson(File.ReadAllText("D:\\MH_Data Repo\\MH_Data\\Parsed Files\\MHWI\\JSONData\\chunk\\common\\item\\itemData.itm.json"));
	}

	internal static class Converter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
